<%@ Page Title="" Language="C#" MasterPageFile="~/ADMIN/Master1.master" AutoEventWireup="true" CodeBehind="ViewProducts.aspx.cs" Inherits="Food2Go.Admin.ViewProducts" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">
        .style2 {
            width: 902px;
        }

        .style3 {
            width: 161px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <table class="tbl" style="width: 100%">
        <tr>
            <td class="tblhead">Food Available
                <asp:Label ID="lblcnt" runat="server"></asp:Label>
            </td>
        </tr>
        <tr>
            <td>
                <table class="style2" style="text-align: center; width: 100%">
                    <tr>
                        <td style="width: 30%"></td>
                        <td class="tblhead">
                            <asp:GridView ID="gvFoodInfo" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" DataKeyNames="pid"
                                AllowPaging="True" PageSize="10" OnPageIndexChanging="gvFoodInfo_PageIndexChanging" BackColor="White" BorderColor="#3366CC" BorderStyle="None" BorderWidth="1px" CellPadding="4" OnRowDeleting="gvFoodInfo_RowDeleting">
                                <Columns>
                                    <asp:CommandField ShowEditButton="True" />
                                    <asp:TemplateField HeaderText="Image">
                                        <ItemTemplate>
                                            <asp:Image ID="imgg" runat="server" ImageUrl='<%#Eval("Image") %>' Height="40px" Width="40px" />
                                        </ItemTemplate>
                                    </asp:TemplateField>
                                    <asp:BoundField DataField="pname" HeaderText="ProductName"
                                        SortExpression="pname" />
                                    <asp:BoundField DataField="price" HeaderText="Price" SortExpression="price" />
                                    <asp:BoundField DataField="detail" HeaderText="Detail"
                                        SortExpression="detail">
                                        <ItemStyle Width="200px" />
                                    </asp:BoundField>
                                    <asp:BoundField DataField="cname" HeaderText="Category"
                                        SortExpression="cname" />
                                </Columns>
                                <FooterStyle BackColor="#99CCCC" ForeColor="#003399" />
                                <HeaderStyle BackColor="#003399" Font-Bold="True" ForeColor="#CCCCFF" />
                                <PagerStyle BackColor="#99CCCC" ForeColor="#003399" HorizontalAlign="Left" />
                                <RowStyle BackColor="White" ForeColor="#003399" />
                                <SelectedRowStyle BackColor="#009999" Font-Bold="True" ForeColor="#CCFF99" />
                                <SortedAscendingCellStyle BackColor="#EDF6F6" />
                                <SortedAscendingHeaderStyle BackColor="#0D4AC4" />
                                <SortedDescendingCellStyle BackColor="#D6DFDF" />
                                <SortedDescendingHeaderStyle BackColor="#002876" />
                            </asp:GridView>
                        </td>

                    </tr>
                </table>
            </td>
        </tr>
    </table>
</asp:Content>
